### ISSUE TITLE
rakam tanıma

### ISSUE THREAD

**Issue by kubraaa** [yerenutku/OCR#1]
merhaba programınızı eclipste açtım inceledim ..
Programınız sizin lokastonunu verdiğiniz  bi,r resimimi açıyor  yoksa herhangi bir resim açıyo mu 
,bide abc karakterlerini mi okuyo yalnız ?
teşekkürler

**Comment by yerenutku** [comment]
Merhaba,
Öncelikle tüm karakterlerin olduğu bir öğretici resim eklememiz gerekiyor yapay sinir ağını eğitmek için(font farklılıklarını ayırt edebilmek için bu şart). Sonrasında verilen resimde karakterleri tanıması bekleniyor. Biz eğitim verisi olarak bir kaç harf denedik ( harf sayısı arttıkça süre uzar). Fakat yapay sinir ağı düzgün eğitilmesine rağmen karakter tanıması, bir önceki eğitim verisinin bir sonraki eğitim verisini bozarak ilerlemesi sonucu tanıyabildiği karakter sayısı sınırlı kalıyor. Bir süre burada tıkandıktan sonra, derslerin yoğunluğu ile birlikte projeyi askıya aldık.
